name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        python-version: ['3.9', '3.12']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip, setuptools, and packaging
      run: |
        python -m pip install --upgrade pip setuptools packaging
    
    - name: Install package with tests
      run: |
        pip install matplotlib
        pip install .[tests]
    
    - name: Run plot example
      run: |
        python3 sigProfilerPlotting/examples/plot_example.py
    
    - name: Run unit tests
      run: |
        pytest -s -rw tests
    
    - name: Build and push Docker image
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && matrix.python-version == '3.12'
      run: |
        echo "Starting Docker deployment to GHCR for sigprofilersuite..."
        
        VERSION_TAG=$(grep "VERSION = " setup.py | cut -d'"' -f2)
        
        # Get the repository name and convert it to lowercase
        REPO_NAME=$(basename ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/sigprofilersuite/$REPO_NAME"
        
        echo "Building version: $VERSION_TAG for image: $IMAGE_NAME"
        
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
        
        docker build \
          --build-arg COMMIT_SHA=${{ github.sha }} \
          -t $IMAGE_NAME:$VERSION_TAG \
          -t $IMAGE_NAME:latest .
        
        docker push $IMAGE_NAME:$VERSION_TAG
        docker push $IMAGE_NAME:latest
        
        echo "Docker deployment to GHCR successful"
